util-linux: exclude test_enosys syscalls on older kernels
When using older kernel versions (<5,2,0) we see the following compilation problem:
../tests/helpers/test_enosys.c:82:18: error: '__NR_move_mount' undeclared here (not in a function)
   82 |  { "move_mount", __NR_move_mount },
      |                  ^~~~~~~~~~~~~~~
../tests/helpers/test_enosys.c:83:17: error: '__NR_open_tree' undeclared here (not in a function)
   83 |  { "open_tree", __NR_open_tree },
      |                 ^~~~~~~~~~~~~~
../tests/helpers/test_enosys.c:84:14: error: '__NR_fsopen' undeclared here (not in a function)
   84 |  { "fsopen", __NR_fsopen },

This is because the mount(2) api syscalls are only supported in kernels starting from v5.2.0.
To fix this, we exclude these syscalls in the tests on util-linux.

GitOrigin-RevId: 578d95993208ef4c949e111f26ba073ceaf38e7e
(cherry picked from commit f3e617a2dbccb6a2360876ceee032a5038bf0e70)