modemmanager: fix dependencies in huawei plugin helpers
This adds the upstream commit https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/commit/2dac0a9e4f145cac5a43b61ed95d9e48b960bf68 as a patch.

The following issue is sometimes observerd without the patch:
../mobile-broadband/ModemManager/src/plugins/huawei/mm-modem-helpers-huawei.c:29:10:
fatal error: mm-huawei-enums-types.h: No such file or directory
   29 | #include "mm-huawei-enums-types.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

GitOrigin-RevId: 3981519ebce277c13a29428745306cd5cccda5f9
(cherry picked from commit f37b51c930543534c921042e47927a8cec8be435)