modemmanager: fix dependencies in huawei plugin helpers
This adds the upstream commit https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/commit/2dac0a9e4f145cac5a43b61ed95d9e48b960bf68 as a patch.

The following issue is sometimes observerd without the patch:
../mobile-broadband/ModemManager/src/plugins/huawei/mm-modem-helpers-huawei.c:29:10:
fatal error: mm-huawei-enums-types.h: No such file or directory
   29 | #include "mm-huawei-enums-types.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

GitOrigin-RevId: e99d9dd5d4d3aff8029921c3d39d830ffd400c64
(cherry picked from commit 5c4fa63f7993f7c598ddf00d2e0be7358be0eefd)