pcm-manager: fix build failure caused by SAH_AMX_PCM_TARBALL
Package fails to build when SAH_AMX_PCM_TARBALL is enabled:

 fs_utils.c:86:10: fatal error: libtar.h: No such file or directory
   86 | #include <libtar.h>
      |          ^~~~~~~~~~

as there is no `libtar` package available. Since we don't use this
feature by default yet anyway, lets disable it completely.

Fixes: PCF-1034
Fixes: 475197c15331 ("network: bump packages")
Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit 79d058c8f9e3f115163050a998f49abfdc4ae718)
(cherry picked from commit c4d25950ef780f7b0e7122f33808c65a914433cf)