[util-linux] disable waitpid
Add a patch to disable compilation of waitpid (there is no proper meson option to disable it).

In openwrt22 util-linux did not have waitpid, this was introduced in https://github.com/util-linux/util-linux/commit/550d32c49e13c219f4e7f895241e0bdcd6fa55ec and only available in the openwrt23 version (v2.39).
The waitpid uses the pidfd_open() function, only available in muslc and not in glibc (https://github.com/util-linux/util-linux/blob/e98ef85a8f934bccac2b984422a40f92955ac97d/misc-utils/waitpid.c#L67C15-L67C25)

Since we build with glibc as well, we get a compilation error:

../misc-utils/waitpid.c: In function 'open_pidfds':
../misc-utils/waitpid.c:67:15: warning: implicit declaration of function 'pidfd_open'; did you mean 'fdopen'? [-Wimplicit-function-declaration]
   pidfds[i] = pidfd_open(pids[i], 0);
               ^~~~~~~~~~
               fdopen
../misc-utils/waitpid.c:67:15: warning: nested extern declaration of 'pidfd_open' [-Wnested-externs]

It looks that there is a wrapper around pidfd_open() using syscall implemented in util-linux: https://github.com/util-linux/util-linux/blob/e98ef85a8f934bccac2b984422a40f92955ac97d/include/pidfd-utils.h#L25
This wrapper should be available when building with glibc, but for some reason some of the ifdefs are obstructing the compiler to get to the function definition.

For now we disable this, but a proper solution should be found.

GitOrigin-RevId: fdf59048fa4f6f2eca3fffd5f146cf588b16c035
(cherry picked from commit 061d23fec2b91786a118b9f981d0b3499d75db28)