swupdate: utilities: uboot-tools: add missing host dependency on python3
Add a host dependency to python3 for both the target and host package
dependencies to ensure that the required Python headers are available.

    SHIPPED scripts/dtc/pylibfdt/libfdt.i
    PYMOD   rebuild
  scripts/dtc/pylibfdt/libfdt_wrap.c:206:11: fatal error: Python.h: No such file or directory
    206 | # include <Python.h>
        |           ^~~~~~~~~~

This dependency is also required when building the target package, as
the upstream U-Boot build generates and builds host-side components
while cross-compiling U-Boot tools for the target.

Fixes: PPW-2104
References: FEAT-29
Signed-off-by: Paul HENRYS <paul.henrys_ext@softathome.com>