python3: Fix ssl support with libressl 3.5
Backport upstream commit bd6e20542199 from https://git.openwrt.org/feed/packages.git:

The branch used by Mediatek projects upstepped libressl in commit 078ad7b70c7d
from https://gitlabinternal.softathome.com/wrt-hgw/buildsystem/prplwrt but it
broke ssl support when compiling Python3 for the host:

  buildsystem/build_dir/hostpkg/Python-3.10.13/Modules/_ssl.c:72:24: error: static declaration of 'SSL_get0_verified_chain' follows non-static declaration
     72 | static STACK_OF(X509) *SSL_get0_verified_chain(const SSL *s)
        |                        ^~~~~~~~~~~~~~~~~~~~~~~
  In file included from buildsystem/build_dir/hostpkg/Python-3.10.13/Modules/_ssl.c:60:
  buildsystem/staging_dir/host/include/openssl/ssl.h:515:17: note: previous declaration of 'SSL_get0_verified_chain' was here
    515 | STACK_OF(X509) *SSL_get0_verified_chain(const SSL *s);

  ...

  Could not build the ssl module!
  Python requires a OpenSSL 1.1.1 or newer
  Custom linker flags may require --with-openssl-rpath=auto

This prevented other host packages to install dependencies with pip that failed.

Issue: SBL-1235 - Prpl MTK - No SSL support in host Python3
GitOrigin-RevId: aeb85ad145c6d172215f06ff144c4cd18c461fc4
(cherry picked from commit de99b8f609ea3a588ff14885bc2b1ae1f4ab30c2)